-- 카테고리 테이블 생성
DROP TABLE IF EXISTS BOOK_CATEGORY;

CREATE TABLE BOOK_CATEGORY (
    id VARCHAR PRIMARY KEY,
    name VARCHAR NOT NULL,
    prefix VARCHAR NOT NULL
);

-- 책 테이블 생성
DROP TABLE IF EXISTS BOOK;

CREATE TABLE BOOK (
    id VARCHAR PRIMARY KEY,
    isbn VARCHAR NOT NULL UNIQUE, -- 도서고유번호(pk로 써도 되는데 왜안씀?)
    name VARCHAR NOT NULL,
    author VARCHAR,
    rental_fee int,
    category_id VARCHAR REFERENCES BOOK_CATEGORY(id)
);

-- 도서관 테이블 생성
DROP TABLE IF EXISTS LIBRARY;

CREATE TABLE LIBRARY (
    id VARCHAR PRIMARY KEY,
    name VARCHAR NOT NULL,
    region VARCHAR
);

-- 도서보유현황 테이블 생성
DROP TABLE IF EXISTS BOOK_LIBRARY_STATUS;

CREATE TABLE BOOK_LIBRARY_STATUS (
    library_id VARCHAR REFERENCES LIBRARY(id),
    book_id VARCHAR REFERENCES BOOK(id),
    remain_count INT NOT NULL,
    total_count INT NOT NULL,
    CONSTRAINT BOOK_LIBRARY_REMAINS_PK PRIMARY KEY (library_id, book_id)
);

-- 도서대여현황 테이블 생성
DROP TABLE IF EXISTS BOOK_RENTAL_HISTORY;

CREATE TABLE BOOK_RENTAL_HISTORY (
    library_id VARCHAR REFERENCES LIBRARY(id),
    book_id VARCHAR REFERENCES BOOK(id),
    client VARCHAR NOT NULL DEFAULT 'N',
    return_yn VARCHAR NOT NULL, -- 기본값 대여안함
--    CONSTRAINT BOOK_RENTAL_HISTORY_PK PRIMARY KEY (library_id, book_id)
);
